version: '3.3'
services:
  app:
    build: .
         dockerfile: C:/Users/pliat/OneDrive/Documents/myPipeline/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my-network
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    networks:
      - my-network

networks:
  my-network:
